''' Creates the production runs automatically for the makefile (a total of 20*2*2 runs; so you might not want to do this by hand)

'''

import numpy as np
masses=[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
f = open("createProductionRuns.txt","w")
for M in masses:
  for r in [1,2]:
    name="M%d_r%d_spin0000"%(M,r)
    mass=M / 10.
    f.write("ProductionData/%s.dat: ../src/growthsampling \n"%name)
    f.write("	OMP_NUM_THREADS=8 $< 1200000 %f 500 0 50 $@ 0 0 0 0.0006671 %d \n"%(mass,r))
    f.write("ProductionData/%s.npz: processData.py ProductionData/%s.dat \n"%(name,name))
    f.write("	python $< ProductionData/%s.dat ProductionData/%s \n"%(name,name))
    f.write("ProductionData/%s.radial: ProductionDataVariables.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s ProductionData/%s.radial \n"%(name,name))
    f.write("# Intermediate results \n")
    f.write("ProductionData/%srho.dat: ../PostProcessing/calculateDensity.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("Plots/%srho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ normal \n"%name)
    f.write("Plots/%slogrho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ log \n"%name)
    f.write("ProductionData/%sGyoto.dat: ../Tests/convertDataToGyoto.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("ProductionData/%sgrid.dat: ../src/rungyoto ProductionData/%sGyoto.dat \n"%(name,name) )
    f.write("	OMP_NUM_THREADS=8 $< runge_kutta_fehlberg78 200 30 1 200 $@ 1 ProductionData/%sGyoto.dat \n"%name)
    f.write("\n")
    name="M%d_r%d_spin0998"%(M,r)
    f.write("ProductionData/%s.dat: ../src/growthsampling \n"%name)
    f.write("	OMP_NUM_THREADS=8 $< 1200000 %f 500 0.998 50 $@ 0 0 0 0.0006671 %d \n"%(mass,r))
    f.write("ProductionData/%s.npz: processData.py ProductionData/%s.dat \n"%(name,name))
    f.write("	python $< ProductionData/%s.dat ProductionData/%s \n"%(name,name))
    f.write("ProductionData/%s.radial: ProductionDataVariables.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s ProductionData/%s.radial \n"%(name,name))
    f.write("# Intermediate results \n")
    f.write("ProductionData/%srho.dat: ../PostProcessing/calculateDensity.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("Plots/%srho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ normal \n"%name)
    f.write("Plots/%slogrho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ log \n"%name)
    f.write("ProductionData/%sGyoto.dat: ../Tests/convertDataToGyoto.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("ProductionData/%sgrid.dat: ../src/rungyoto ProductionData/%sGyoto.dat \n"%(name,name) )
    f.write("	OMP_NUM_THREADS=8 $< runge_kutta_fehlberg78 200 30 1 200 $@ 1 ProductionData/%sGyoto.dat \n"%name)
    f.write("\n")


r = 1
f.write("productionr1data: ")
for M in masses:
  name="M%d_r%d_spin0000"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sGyoto.dat ProductionData/%sgrid.dat "%(name,name,name,name,name,name))
  name="M%d_r%d_spin0998"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sGyoto.dat ProductionData/%sgrid.dat "%(name,name,name,name,name,name))
f.write("\n\n")
f.write("productionr1plots: ")
for M in masses:
  name="M%d_r%d_spin0000"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
  name="M%d_r%d_spin0998"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
f.write("\n\n")
r = 2
f.write("productionr2data: ")
for M in masses:
  name="M%d_r%d_spin0000"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sGyoto.dat ProductionData/%sgrid.dat "%(name,name,name,name,name,name))
  name="M%d_r%d_spin0998"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sGyoto.dat ProductionData/%sgrid.dat "%(name,name,name,name,name,name))
f.write("\n\n")
f.write("productionr2plots: ")
for M in masses:
  name="M%d_r%d_spin0000"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
  name="M%d_r%d_spin0998"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))

f.write("\n\n")

# Create data for the 3D Plots:
import numpy as np
masses=[10]
for M in masses:
  for r in [1]:
    name="M%d_r%d_spin0000"%(M,r)
    mass=M / 10.
    f.write("ProductionData/%s.dat: ../src/growthsampling \n"%name)
    f.write("	OMP_NUM_THREADS=8 $< 1200000 %f 500 0 50 $@ 0 0 0 0.0006671 %d \n"%(mass,r))
    f.write("ProductionData/%s.npz: processData.py ProductionData/%s.dat \n"%(name,name))
    f.write("	python $< ProductionData/%s.dat ProductionData/%s \n"%(name,name))
    f.write("ProductionData/%s.radial: ProductionDataVariables.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s ProductionData/%s.radial \n"%(name,name))
    f.write("# Intermediate results \n")
    f.write("ProductionData/%srho.dat: ../PostProcessing/calculateDensity.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("Plots/%srho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ normal \n"%name)
    f.write("Plots/%slogrho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ log \n"%name)
    f.write("ProductionData/%sGyoto.dat: ../Tests/convertDataToGyoto.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("ProductionData/%sgrid.dat: ../src/rungyoto ProductionData/%sGyoto.dat \n"%(name,name) )
    f.write("	OMP_NUM_THREADS=8 $< runge_kutta_fehlberg78 200 30 1 200 $@ 1 ProductionData/%sGyoto.dat \n"%name)
    f.write("\n")
    name="M%d_r%d_spin0300"%(M,r)
    f.write("ProductionData/%s.dat: ../src/growthsampling \n"%name)
    f.write("	OMP_NUM_THREADS=8 $< 1200000 %f 500 0.3 50 $@ 0 0 0 0.0006671 %d \n"%(mass,r))
    f.write("ProductionData/%s.npz: processData.py ProductionData/%s.dat \n"%(name,name))
    f.write("	python $< ProductionData/%s.dat ProductionData/%s \n"%(name,name))
    f.write("ProductionData/%s.radial: ProductionDataVariables.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s ProductionData/%s.radial \n"%(name,name))
    f.write("# Intermediate results \n")
    f.write("ProductionData/%srho.dat: ../PostProcessing/calculateDensity.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("Plots/%srho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ normal \n"%name)
    f.write("Plots/%slogrho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ log \n"%name)
    f.write("ProductionData/%sGyoto.dat: ../Tests/convertDataToGyoto.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("ProductionData/%sgrid.dat: ../src/rungyoto ProductionData/%sGyoto.dat \n"%(name,name) )
    f.write("	OMP_NUM_THREADS=8 $< runge_kutta_fehlberg78 200 30 1 200 $@ 1 ProductionData/%sGyoto.dat \n"%name)

    f.write("\n")
    name="M%d_r%d_spin0600"%(M,r)
    f.write("ProductionData/%s.dat: ../src/growthsampling \n"%name)
    f.write("	OMP_NUM_THREADS=8 $< 1200000 %f 500 0.6 50 $@ 0 0 0 0.0006671 %d \n"%(mass,r))
    f.write("ProductionData/%s.npz: processData.py ProductionData/%s.dat \n"%(name,name))
    f.write("	python $< ProductionData/%s.dat ProductionData/%s \n"%(name,name))
    f.write("ProductionData/%s.radial: ProductionDataVariables.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s ProductionData/%s.radial \n"%(name,name))
    f.write("# Intermediate results \n")
    f.write("ProductionData/%srho.dat: ../PostProcessing/calculateDensity.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("Plots/%srho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ normal \n"%name)
    f.write("Plots/%slogrho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ log \n"%name)
    f.write("ProductionData/%sGyoto.dat: ../Tests/convertDataToGyoto.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("ProductionData/%sgrid.dat: ../src/rungyoto ProductionData/%sGyoto.dat \n"%(name,name) )
    f.write("	OMP_NUM_THREADS=8 $< runge_kutta_fehlberg78 200 30 1 200 $@ 1 ProductionData/%sGyoto.dat \n"%name)
    f.write("\n")
    name="M%d_r%d_spin0998"%(M,r)
    f.write("ProductionData/%s.dat: ../src/growthsampling \n"%name)
    f.write("	OMP_NUM_THREADS=8 $< 1200000 %f 500 0.998 50 $@ 0 0 0 0.0006671 %d \n"%(mass,r))
    f.write("ProductionData/%s.npz: processData.py ProductionData/%s.dat \n"%(name,name))
    f.write("	python $< ProductionData/%s.dat ProductionData/%s \n"%(name,name))
    f.write("ProductionData/%s.radial: ProductionDataVariables.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s ProductionData/%s.radial \n"%(name,name))
    f.write("# Intermediate results \n")
    f.write("ProductionData/%srho.dat: ../PostProcessing/calculateDensity.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("Plots/%srho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ normal \n"%name)
    f.write("Plots/%slogrho.pdf: ../PostProcessing/plotDensity.py ProductionData/%srho.dat \n"%(name,name))
    f.write("	python $< ProductionData/%srho.dat $@ log \n"%name)
    f.write("ProductionData/%sGyoto.dat: ../Tests/convertDataToGyoto.py ProductionData/%s.npz \n"%(name,name))
    f.write("	python $< ProductionData/%s $@ \n"%name)
    f.write("ProductionData/%sgrid.dat: ../src/rungyoto ProductionData/%sGyoto.dat \n"%(name,name) )
    f.write("	OMP_NUM_THREADS=8 $< runge_kutta_fehlberg78 200 30 1 200 $@ 1 ProductionData/%sGyoto.dat \n"%name)
    f.write("\n")


r = 1
f.write("production3ddata: ")
for M in masses:
  name="M%d_r%d_spin0000"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sgrid.dat "%(name,name,name,name,name))
  name="M%d_r%d_spin0300"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sgrid.dat "%(name,name,name,name,name))
  name="M%d_r%d_spin0600"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sgrid.dat "%(name,name,name,name,name))
  name="M%d_r%d_spin0998"%(M,r)
  f.write("ProductionData/%s.dat ProductionData/%s.npz ProductionData/%srho.dat ProductionData/%s.radial ProductionData/%sgrid.dat "%(name,name,name,name,name))
f.write("\n\n")
f.write("production3dplots: ")
for M in masses:
  name="M%d_r%d_spin0000"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
  name="M%d_r%d_spin0300"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
  name="M%d_r%d_spin0600"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
  name="M%d_r%d_spin0998"%(M,r)
  f.write("Plots/%srho.pdf Plots/%slogrho.pdf "%(name,name))
f.write("\n\n")
f.close()

